#!/bin/bash

# ===========================================
# BUKO AI - DOCKER HELP SCRIPT
# ===========================================

echo "🐳 Buko AI Docker Commands"
echo "=========================="
echo ""
echo "📦 Development:"
echo "  docker-compose -f docker-compose.dev.yml up --build"
echo "  docker-compose -f docker-compose.dev.yml down"
echo ""
echo "🚀 Production:"
echo "  docker-compose -f docker-compose.prod.yml up -d --build"
echo "  docker-compose -f docker-compose.prod.yml down"
echo ""
echo "🔧 Individual services:"
echo "  docker-compose up web"
echo "  docker-compose up worker"
echo "  docker-compose up beat"
echo "  docker-compose up flower"
echo ""
echo "📊 Monitoring:"
echo "  docker-compose logs -f web"
echo "  docker-compose logs -f worker"
echo "  docker-compose exec web flask shell"
echo ""
echo "🗄️ Database:"
echo "  docker-compose exec db psql -U user -d buko_ai"
echo "  docker-compose exec web flask db upgrade"
echo ""
echo "🧪 Testing:"
echo "  docker-compose exec web pytest"
echo "  docker-compose exec web python -m pytest tests/"
echo ""
echo "🧹 Cleanup:"
echo "  docker-compose down -v"
echo "  docker system prune -f"
echo "  docker volume prune -f"
echo ""